// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHvSP0eimAcFVH6Z0i3w_saAhRSdOn0Gw',
    appId: '1:218964289421:web:80fa41a25ab2ece727bfc4',
    messagingSenderId: '218964289421',
    projectId: 'payapp-cf99c',
    authDomain: 'payapp-cf99c.firebaseapp.com',
    storageBucket: 'payapp-cf99c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGeJtQ8lGh5gEgC8nLu-c8dAepkzlFwPQ',
    appId: '1:218964289421:android:a52dba1b0bba632827bfc4',
    messagingSenderId: '218964289421',
    projectId: 'payapp-cf99c',
    storageBucket: 'payapp-cf99c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_3lIsPvW_tPLC37QybKwxQFtNdFFPU6Y',
    appId: '1:218964289421:ios:faf0dc607f25e0fe27bfc4',
    messagingSenderId: '218964289421',
    projectId: 'payapp-cf99c',
    storageBucket: 'payapp-cf99c.firebasestorage.app',
    iosBundleId: 'com.example.quickmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_3lIsPvW_tPLC37QybKwxQFtNdFFPU6Y',
    appId: '1:218964289421:ios:faf0dc607f25e0fe27bfc4',
    messagingSenderId: '218964289421',
    projectId: 'payapp-cf99c',
    storageBucket: 'payapp-cf99c.firebasestorage.app',
    iosBundleId: 'com.example.quickmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHvSP0eimAcFVH6Z0i3w_saAhRSdOn0Gw',
    appId: '1:218964289421:web:bfc6d9784fa97c1a27bfc4',
    messagingSenderId: '218964289421',
    projectId: 'payapp-cf99c',
    authDomain: 'payapp-cf99c.firebaseapp.com',
    storageBucket: 'payapp-cf99c.firebasestorage.app',
  );
}
